swagger: '2.0'
info:
  title: Argent Bank API documentation (phase 2)
  description: A proposal for transactions endpoints of the API
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API (updated version)
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      # produces:
      #   - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/{accountId}/transactions:
    get:
      tags:
        - Account Module
      summary: Access account transactions by ID
      description: Returns all transactions of an account
      operationId: getTransactionsById
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
          # schema:
          #   type: integer
          #   format: int64
      responses:
        '200':
          description: successful operation
          # content:
          #   application/json:
          schema:
            $ref: '#/definitions/Transactions'
          # application/xml:
          #   schema:
          #     $ref: '#/definitions/Transactions'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  /account/{accountId}/transactions/{transactionID}:
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account Transaction API
      description: API for updating a transaction
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
        - name: transactionID
          in: path
          type: string
          description: ID of the selected transaction
          required: true
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update account transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction info retrieved successfully
          schema:
            $ref: '#/definitions/TransactionInfo'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  Transactions:
    type: object
    properties:
      transaction:
        type: object
        properties:
          primaryInfo:
            type: object
            properties:
              id:
                type: number
              date:
                type: string
              description:
                type: string
              amount:
                type: string
              balance:
                type: string
          secondaryInfo:
            type: object
            properties:
              type:
                type: string
              category:
                type: string
              notes:
                type: string
  TransactionInfo:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
