swagger: '2.0'
info:
  title: Argent Bank API documentation (phase 2)
  description: A proposal for transactions endpoints of the API
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/{accountId}/transactions:
    get:
      tags:
        - Account Module
      summary: Access account transactions by ID
      description: Returns all transactions of an account
      operationId: getTransactionsById
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
        - in: query
          name: date
          type: string
          required: false
          pattern: /([0-9]{4})-(?:[0-9]{2})/
          description: Get the transactions of a month with param of the form "YYYY-MM".
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
    post:
      tags:
        - Account Module
      summary: Create a new transaction
      description: Add a new transaction
      operationId: addTransaction
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
        - in: body
          name: body
          description: Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/NewTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction added successfully
          schema:
            $ref: '#/definitions/NewTransactionApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts/{accountId}/transactions/{transactionID}:
    get:
        tags:
          - Account Module
        summary: Access a transaction by ID
        description: Returns a transaction of an account
        operationId: getTransactionById
        parameters:
          - name: accountId
            in: path
            type: string
            description: ID of the selected account
            required: true
          - name: transactionID
            in: path
            type: string
            description: ID of the selected transaction
            required: true
        responses:
          '200':
            description: successful operation
            schema:
              $ref: '#/definitions/Transaction'
          '400':
            description: Invalid ID supplied
          '404':
            description: Transaction not found
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Update a transaction by ID
      description: API for updating a transaction
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
        - name: transactionID
          in: path
          type: string
          description: ID of the selected transaction
          required: true
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update account transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction info retrieved successfully
          schema:
            $ref: '#/definitions/TransactionInfo'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Account Module
      summary: Delete a transaction by ID
      description: API for deleting a transaction
      operationId: deleteTransaction
      parameters:
        - name: accountId
          in: path
          type: string
          description: ID of the selected account
          required: true
        - name: transactionID
          in: path
          type: string
          description: ID of the transaction that needs to be deleted
          required: true
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: array
    items:
      $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      transaction:
        type: object
        properties:
          primaryInfo:
            type: object
            properties:
              id:
                type: number
              date:
                type: string
              description:
                type: string
              amount:
                type: string
              balance:
                type: string
          secondaryInfo:
            type: object
            properties:
              type:
                type: string
              category:
                type: string
              notes:
                type: string
  TransactionInfo:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  NewTransaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: string
      balance:
        type: string
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  NewTransactionApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'
